<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251227161924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meal_plan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, validated BOOLEAN NOT NULL, user_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C7848889A76ED395 ON meal_plan (user_id)');
        $this->addSql('CREATE INDEX IDX_C784888959D8A214 ON meal_plan (recipe_id)');
        $this->addSql('CREATE INDEX idx_meal_plan_user_date ON meal_plan (user_id, date)');
        $this->addSql('CREATE INDEX idx_meal_plan_user_validated ON meal_plan (user_id, validated)');
        $this->addSql('CREATE UNIQUE INDEX uniq_meal_plan_user_recipe_date ON meal_plan (user_id, recipe_id, date)');
        $this->addSql('ALTER TABLE meal_plan ADD CONSTRAINT FK_C7848889A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_plan ADD CONSTRAINT FK_C784888959D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_ingredient_name_key');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify i
        $this->addSql('ALTER TABLE meal_plan DROP CONSTRAINT FK_C7848889A76ED395');
        $this->addSql('ALTER TABLE meal_plan DROP CONSTRAINT FK_C784888959D8A214');
        $this->addSql('DROP TABLE meal_plan');
        $this->addSql('CREATE UNIQUE INDEX uniq_ingredient_name_key ON ingredient (name_key)');
    }
}
