<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260108165105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_meal_suggestion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, status VARCHAR(32) NOT NULL, context VARCHAR(32) NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, meta JSON DEFAULT NULL, user_id INT NOT NULL, meal_plan_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EAC4777F912AB082 ON daily_meal_suggestion (meal_plan_id)');
        $this->addSql('CREATE INDEX idx_daily_suggestion_date ON daily_meal_suggestion (date)');
        $this->addSql('CREATE INDEX idx_daily_suggestion_user ON daily_meal_suggestion (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_daily_suggestion_user_date ON daily_meal_suggestion (user_id, date)');
        $this->addSql('ALTER TABLE daily_meal_suggestion ADD CONSTRAINT FK_EAC4777FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_meal_suggestion ADD CONSTRAINT FK_EAC4777F912AB082 FOREIGN KEY (meal_plan_id) REFERENCES meal_plan (id) ON DELETE SET NULL NOT DEFERRABLE');
        
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        
        $this->addSql('ALTER TABLE daily_meal_suggestion DROP CONSTRAINT FK_EAC4777FA76ED395');
        $this->addSql('ALTER TABLE daily_meal_suggestion DROP CONSTRAINT FK_EAC4777F912AB082');
        $this->addSql('DROP TABLE daily_meal_suggestion');
    
    }
}
