<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251230210245 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shopping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(10, 2) NOT NULL, source VARCHAR(16) NOT NULL, checked BOOLEAN NOT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, ingredient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB45F439A76ED395 ON shopping (user_id)');
        $this->addSql('CREATE INDEX IDX_FB45F439933FE08C ON shopping (ingredient_id)');
        $this->addSql('ALTER TABLE shopping ADD CONSTRAINT FK_FB45F439A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shopping ADD CONSTRAINT FK_FB45F439933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shopping DROP CONSTRAINT FK_FB45F439A76ED395');
        $this->addSql('ALTER TABLE shopping DROP CONSTRAINT FK_FB45F439933FE08C');
        $this->addSql('DROP TABLE shopping');
    }
}
