<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260108165105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE graphql.seq_schema_version CASCADE');
        $this->addSql('CREATE TABLE daily_meal_suggestion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, status VARCHAR(32) NOT NULL, context VARCHAR(32) NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, meta JSON DEFAULT NULL, user_id INT NOT NULL, meal_plan_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EAC4777F912AB082 ON daily_meal_suggestion (meal_plan_id)');
        $this->addSql('CREATE INDEX idx_daily_suggestion_date ON daily_meal_suggestion (date)');
        $this->addSql('CREATE INDEX idx_daily_suggestion_user ON daily_meal_suggestion (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_daily_suggestion_user_date ON daily_meal_suggestion (user_id, date)');
        $this->addSql('ALTER TABLE daily_meal_suggestion ADD CONSTRAINT FK_EAC4777FA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_meal_suggestion ADD CONSTRAINT FK_EAC4777F912AB082 FOREIGN KEY (meal_plan_id) REFERENCES meal_plan (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_ingredient_global_name_key');
        $this->addSql('ALTER TABLE ingredient ADD img_generated BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE ingredient ADD img_generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE recipe ADD img_generated BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE recipe ADD img_generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_ingredient ON shopping (user_id, ingredient_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA receiplan');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE SEQUENCE graphql.seq_schema_version INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE daily_meal_suggestion DROP CONSTRAINT FK_EAC4777FA76ED395');
        $this->addSql('ALTER TABLE daily_meal_suggestion DROP CONSTRAINT FK_EAC4777F912AB082');
        $this->addSql('DROP TABLE daily_meal_suggestion');
        $this->addSql('ALTER TABLE ingredient DROP img_generated');
        $this->addSql('ALTER TABLE ingredient DROP img_generated_at');
        $this->addSql('CREATE UNIQUE INDEX uniq_ingredient_global_name_key ON ingredient (name_key) WHERE (user_id IS NULL)');
        $this->addSql('ALTER TABLE recipe DROP img_generated');
        $this->addSql('ALTER TABLE recipe DROP img_generated_at');
        $this->addSql('DROP INDEX uniq_user_ingredient');
    }
}
