<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113204020 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

        $this->addSql('CREATE TABLE meal_cooked_prompt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, status VARCHAR(16) NOT NULL, answer VARCHAR(8) DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, answered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, context VARCHAR(64) NOT NULL, user_id INT NOT NULL, meal_plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527C1AF1A76ED395 ON meal_cooked_prompt (user_id)');
        $this->addSql('CREATE INDEX IDX_527C1AF1912AB082 ON meal_cooked_prompt (meal_plan_id)');
        $this->addSql('CREATE INDEX idx_meal_cooked_prompt_status_date ON meal_cooked_prompt (status, date)');
        $this->addSql('CREATE INDEX idx_meal_cooked_prompt_user_status ON meal_cooked_prompt (user_id, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_meal_cooked_prompt_user_date ON meal_cooked_prompt (user_id, date)');
        $this->addSql('ALTER TABLE meal_cooked_prompt ADD CONSTRAINT FK_527C1AF1A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meal_cooked_prompt ADD CONSTRAINT FK_527C1AF1912AB082 FOREIGN KEY (meal_plan_id) REFERENCES meal_plan (id) ON DELETE CASCADE NOT DEFERRABLE');
    
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
    
        $this->addSql('ALTER TABLE meal_cooked_prompt DROP CONSTRAINT FK_527C1AF1A76ED395');
        $this->addSql('ALTER TABLE meal_cooked_prompt DROP CONSTRAINT FK_527C1AF1912AB082');
        $this->addSql('DROP TABLE meal_cooked_prompt');
    
    }
}
