<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260117203245 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assistant_conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BF3529BA76ED395 ON assistant_conversation (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_day ON assistant_conversation (user_id, day)');
        $this->addSql('CREATE TABLE assistant_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, content TEXT NOT NULL, payload JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A36E1EF9AC0396 ON assistant_message (conversation_id)');
        $this->addSql('CREATE INDEX idx_conversation_created ON assistant_message (conversation_id, created_at)');
        $this->addSql('ALTER TABLE assistant_conversation ADD CONSTRAINT FK_5BF3529BA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assistant_message ADD CONSTRAINT FK_8A36E1EF9AC0396 FOREIGN KEY (conversation_id) REFERENCES assistant_conversation (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assistant_conversation DROP CONSTRAINT FK_5BF3529BA76ED395');
        $this->addSql('ALTER TABLE assistant_message DROP CONSTRAINT FK_8A36E1EF9AC0396');
        $this->addSql('DROP TABLE assistant_conversation');
        $this->addSql('DROP TABLE assistant_message');
    }
}
